// List Methods

void main() {
  List<String> listA = ['red', 'green', 'blue', 'red'];
  List<int> listB = [50, 60, 70];
  List<dynamic> listC = ['red', 'blue', 20, 50];
  // listA.add('blue');
  // print(listA);
  // listA.addAll(['yellow', 'black']);
  // print(listA);
  // listA.clear();
  // print(listA);
  // listA.fillRange(0, 3, 'black');
  // print(listA);
  // print(listA.getRange(1, 3));
  // print(listA.getRange(0, 3).toList());
  // print(listA.indexOf('red'));
  // print(listA.indexOf('red', 1));
  // print(listA.indexWhere((element) => element == 'blue'));
  // listA.insert(3, 'black');
  // print(listA);
  // listA.insertAll(1, ['white', 'yello']);
  // print(listA);
  // print(listA.lastIndexOf('red'));
  // print(listA.lastIndexWhere((element) => element == 'red'));
  // listA.remove('green');
  // print(listA);
  // listA.removeAt(2);
  // print(listA);
  // listA.removeLast();
  // print(listA);
  // listA.removeRange(0, 3);
  // print(listA);
  // listA.removeWhere((element) => element == 'red');
  // listA.replaceRange(0, 2, ['orange', 'black']);
  // print(listA);
  // listA.retainWhere((element) => element == 'green');
  // print(listA);
  // listA.setAll(0, ['blue', 'yello', 'white']);
  // print(listA);
  // listA.setRange(0, 3, ['blue', 'blue', 'blue']);
  // print(listA);
  // listA.shuffle();
  // print(listA);
  // listA.sort();
  // print(listA);
  // print(listA.sublist(0, 2));
  // print(listA.sublist(2));
  // print(listA.any((element) => element == 'red'));
  // print(listA.contains('green'));
  // print(listA[1]);
  // print(listA.elementAt(2));
  // print(listB.every((element) => element > 10));
  // print(listB.expand((element) => [element, element * element].toList()));
  // print(listA.firstWhere((element) => element == 'blue', orElse: ()=> 'no element'));
  // print(listB.fold(0, (a, b) => b + a));
  // listB.forEach((element) {print(element);});
  // print(listA.join());
  // print(listA.join(' '));
  // print(listA.join(', '));
  // print(listB.lastIndexWhere((element) => element % 5 == 0));
  // print(listB.reduce((a, b) => b + a));
  // print(listA.singleWhere((element) => element == 'black', orElse: () => 'no element'));
  // print(listA.skip(2).toList());
  // print(listA.skipWhile((value) => value == 'red').toList());
  // print(listA.take(1).toList());
  // print(listA.takeWhile((value) => value == 'red').toList());
  // print(listA.where((element) => element == 'blue').toList());
  print(listC.whereType<String>().toList());
}
